### PR TITLE
Kubernetes example

### PR DESCRIPTION
**Pull request by mhaluska**
### Example k8s deployment.

**Deployment steps:**

- update `examples/k8s/ingress.yaml` with your domain.
- ensure you've some dynamic provisioner for `storage` and `elasticsearch`, otherwise configure storage before
- $ kubectl create namespace lodestone
- $ kubectl apply -f examples/k8s/

### CODE REVIEW

**Comment by AnalogJ** [comment]
Oh this is great! Thanks for the PR 🎉 

I'm actually in the process of stripping out the reverse proxy, which resulted in the addition of a bunch more environmental variables. Can you take a look at the docker-compose file in the `beta2` branch and see if some of those changes need to be migrated into your kubernetes config?

Thanks again!

**Comment by mhaluska** [comment]
Looks fine, I think I'll just need update ingress for /storage path when proxied already by webapp.
I see you added possibility to change `hostname` and `port` for connections, anyway this will not impact k8s files, services are defined. Just I see you've replacement if variable is not set, are you using also defaults inside apps? Otherwise I'll need add those vars there.

**Comment by AnalogJ** [comment]
Unfortunately I'm not setting the defaults inside the apps, just in the docker-compose, so they need to be set by the orchestration tool.

**Comment by mhaluska** [comment]
Ok, so I'll update k8s deployment files.

**Comment by mhaluska** [comment]
I updated examples, so all env vars should be there now.

**Comment by AnalogJ** [comment]
Awesome. I'll merge this when beta2 is merged (probably this weekend) 
Thanks @mhaluska!

**Pull request merged**
